api_platform:
    mapping:
        paths: 
          #- "%kernel.project_dir%/src/Entity"
          - "%kernel.project_dir%/src/Resources/config/api_resources"
    title: "Altar API"
    description: "Private dev API for Altar Gallery based applications."
    version: 0.2.0
    eager_loading:
        enabled: true
        fetch_partial: false
        force_eager: false
    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']
        html:
            mime_types: ['text/html']