App\Entity\Channel:
  collectionOperations:
    # User
    get:
      method: GET
      normalization_context:
        groups: [ "ch.get" ]
    # Admin
    admin_get:
      method: GET
      path: "/admin/channels"
    admin_post:
      method: POST
      path: "/admin/channels"
  itemOperations:
    # User
    get:
      method: GET
      normalization_context:
        groups: [ "ch.get" ]
    # Admin
    admin_get:
      method: GET
      path: "/admin/channel/{id}"
    admin_put:
      method: PUT
      path: "/admin/channel/{id}"
    admin_delete:
      method: DELETE
      path: "/admin/channel/{id}"

App\Entity\Post:
  collectionOperations:
    # User
    get:
      method: GET
      normalization_context:
        groups: [ "p.get" ]
    post:
      method: POST
      denormalization_context:
        groups: [ "p.post" ]
      normalization_context:
        groups: [ "p.get" ]
    api_channels_posts_get_subresource:
      method: GET
      normalization_context:
        groups: [ "p.get" ]
    # Admin
    admin_get:
      method: GET
      path: "/admin/posts"
    admin_post:
      method: POST
      path: "/admin/posts"
  itemOperations:
    # User
    get:
      method: GET
      normalization_context:
        groups: [ "p.get" ]
    # Admin
    admin_get:
      method: GET
      path: "/admin/posts/{id}"
    admin_put:
      method: PUT
      path: "/admin/posts/{id}"
    admin_delete:
      method: DELETE
      path: "/admin/posts/{id}"
    # User

App\Entity\Comment:
  collectionOperations:
    get:
      method: GET
      normalization_context:
        groups: [ "c.get" ]
    post:
      method: POST
      normalization_context:
        groups: [ "c.post" ]
  itemOperations:
    get:
      method: GET
      normalization_context:
        groups: [ "c.get" ]
    put:
      method: PUT
      denormalization_context:
        groups: [ "c.put" ]
    delete:
      method: DELETE

App\Entity\PostType:
  collectionOperations:
    get:
      method: GET
      normalization_context:
        groups: [ "post_types.get" ]
    post:
      method: POST
      normalization_context:
        groups: [ "post_types.post" ]
  itemOperations:
    get:
      method: GET
      normalization_context:
        groups: [ "post_type.get" ]
    put:
      method: PUT
      denormalization_context:
        groups: [ "post_type.put" ]
    delete:
      method: DELETE

App\Entity\Role:
  collectionOperations:
    get:
      method: GET
      normalization_context:
        groups: [ "roles.get" ]
    post:
      method: POST
      normalization_context:
        groups: [ "roles.post" ]
  itemOperations:
    get:
      method: GET
      normalization_context:
        groups: [ "role.get" ]
    put:
      method: PUT
      denormalization_context:
        groups: [ "role.put" ]
    delete:
      method: DELETE

App\Entity\User:
  collectionOperations:
    get:
      method: GET
      normalization_context:
        groups: [ "users.get" ]
    post:
      method: POST
      normalization_context:
        groups: [ "users.post" ]
  itemOperations:
    get:
      method: GET
      normalization_context:
        groups: [ "user.get" ]
    put:
      method: PUT
      denormalization_context:
        groups: [ "user.put" ]
    delete:
      method: DELETE

App\Entity\Vote:
  collectionOperations:
    get:
      method: GET
      normalization_context:
        groups: [ "votes.get" ]
    post:
      method: POST
      normalization_context:
        groups: [ "votes.post" ]
  itemOperations:
    get:
      method: GET
      normalization_context:
        groups: [ "vote.get" ]
    put:
      method: PUT
      denormalization_context:
        groups: [ "vote.put" ]
    delete:
      method: DELETE
