App\Entity\Channel:
  collectionOperations:
    # User
    get:
      method: GET
      normalization_context:
        groups: [ "ch.get" ]
    # Admin
    admin_get:
      method: GET
      path: "/admin/channels"
    admin_post:
      method: POST
      path: "/admin/channels"
  itemOperations:
    # Admin
    admin_get:
      method: GET
      path: "/admin/channel/{id}"
    admin_put:
      method: PUT
      path: "/admin/channel/{id}"
    admin_delete:
      method: DELETE
      path: "/admin/channel/{id}"

App\Entity\Post:
  collectionOperations:
    # User
    # get:
    #   method: GET
    #   normalization_context:
    #     groups: [ "p.get" ]
    post:
      method: POST
      denormalization_context:
        groups: [ "p.post" ]
      normalization_context:
        groups: [ "p.get" ]

    # Admin
    admin_get:
      method: GET
      path: "/admin/posts"
    admin_post:
      method: POST
      path: "/admin/posts"
  itemOperations:
    # User
    get:
      method: GET
      normalization_context:
        groups: [ "p.get" ]
    # Admin
    admin_get:
      method: GET
      path: "/admin/posts/{id}"
    admin_put:
      method: PUT
      path: "/admin/posts/{id}"
    admin_delete:
      method: DELETE
      path: "/admin/posts/{id}"

App\Entity\Comment:
  collectionOperations:
    # Admin
    admin_get:
      method: GET
      path: "/admin/comments"
    admin_post:
      method: POST
      path: "/admin/comments"
  itemOperations:
    # Admin
    admin_get:
      method: GET
      path: "/admin/comments/{id}"
    admin_put:
      method: PUT
      path: "/admin/comments/{id}"
    admin_delete:
      method: DELETE
      path: "/admin/comments/{id}"

App\Entity\PostType:
  collectionOperations:
    # Admin
    admin_get:
      method: GET
      path: "/admin/post_types"
    post:
      method: POST
      path: "/admin/post_types"
  itemOperations:
    # Admin
    get:
      method: GET
      path: "/admin/post_types/{id}"
    put:
      method: PUT
      path: "/admin/post_types/{id}"
    delete:
      method: DELETE
      path: "/admin/post_types/{id}"

App\Entity\Role:
  collectionOperations:
    # Admin
    get:
      method: GET
      path: "/admin/roles"
    post:
      method: POST
      path: "/admin/roles"
  itemOperations:
    # Admin
    get:
      method: GET
      path: "/admin/roles/{id}"
    put:
      method: PUT
      path: "/admin/roles/{id}"
    delete:
      method: DELETE
      path: "/admin/roles/{id}"

App\Entity\User:
  collectionOperations:
    # Admin
    get:
      method: GET
      path: "/admin/users"
      normalization_context:
        groups: [ "u.admin.get" ]
    post:
      method: POST
      path: "/admin/users"
      denormalization_context:
        groups: [ "u.admin.post" ]
      normalization_context:
        groups: [ "u.admin.get" ]
  itemOperations:
    # User
    get:
      method: GET
      normalization_context:
        groups: [ "u.get" ]
    # Admin
    get:
      method: GET
      path: "/admin/users/{id}"
      normalization_context:
        groups: [ "u.admin.get" ]
    put:
      method: PUT
      path: "/admin/users/{id}"
      denormalization_context:
        groups: [ "u.admin.put" ]
      normalization_context:
        groups: [ "u.admin.get" ]
    delete:
      method: DELETE
      path: "/admin/users/{id}"

App\Entity\Vote:
  collectionOperations:
    # User
    post:
      method: POST
      denormalization_context:
        groups: [ "v.post" ]
      normalization_context:
        groups: [ "v.post" ]
    # Admin
    get:
      method: GET
      path: "/admin/votes"
    post:
      method: POST
      path: "/admin/votes"
  itemOperations:
    # Admin
    get:
      method: GET
      path: "/admin/votes/{id}"
    put:
      method: PUT
      path: "/admin/votes/{id}"
    delete:
      method: DELETE
      path: "/admin/votes/{id}"
